name: 'Actions terminal'

on:
  push:
    branches: ['develop', 'staging']
  pull_request:
    branches: ['develop', 'staging']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rodar um echo
        run: echo actions message
