name: "CI (Interação Continua): Testes"

on:
  push:
    branches: [ "develop", "staging"]
  pull_request:
    branches: [ "develop", "staging"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependencias
        run: yarn install

      - name: Rodar testes
        run: yarn test
